# Generated by Django 5.0.6 on 2024-07-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='explainer',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
